### PR TITLE
Refactor GraphicEntityModule by exracting serializer to a smaller class.

### PR DESCRIPTION
**Pull request by A4Vision**

### CODE REVIEW

**Comment by A4Vision** [comment]
Hello @nantoniazzi , would you like to review this PR ?

**Comment by refactormachine** [comment]
I see your point, the class game.entities.serializer is used only here.

So I moved the function `dumpWorldStateDiff` into WorldState and renamed it as 
`serializeDiffFromPrevWorldState`. More, I refactored it to be more readable.

What do you think @CGjupoulton ?

**Comment by CGjupoulton** [comment]
It is indeed more readable, but I don't like seeing a "serialize" method other than in the Serializer class. 
I think I'll rename `serializeDiffFromPrevWorldState()` to `diffFromOtherWorldState()`. It will be more consistent with `EntityStates`'s  `diffFromOtherState()`.

**Comment by CGjupoulton** [comment]
To summarize my previous comment, I think the WorldState diff function should act the same as the EntityState diff function. Namely, a new state is created with only the differences, then that is passed to the Serializer.

**Pull request merged**
